language: cpp

sudo: false


compiler:
  - gcc
  - clang

cache: apt


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=true"
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false -DWITH_ITK=false"
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libboost-program-options-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libboost-system-dev
    - libgmp-dev
    - libgdcm2-dev 
    - libgraphicsmagick++1-dev
    - libqglviewer-qt4-dev
    - libinsighttoolkit3-dev 
before_script:
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal
  - mkdir LibDGtal
  - cmake . $DGTALTYPE -DCMAKE_INSTALL_PREFIX:PATH=$PWD/LibDGtal 
  - make & make DESTDIR=$PWD/LibDGtal install
  - cd ..

script: 
   - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/LibDGtal
   - make
