language: cpp

sudo: false


compiler:
  - gcc
  - clang

cache: apt


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=true"
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false -DWITH_ITK=false"
addons:
  apt:
    packages:
    - libboost-program-options-dev
    - libboost-system-dev
    - libqglviewer-qt4-dev
    - libinsighttoolkit3-dev
    - libgdcm2-dev


before_script:
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal
  - cmake . $DGTALTYPE  
  - make 
  - cd ..

script: 
   - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD//DGtal/build/
   - make
