language: cpp

sudo: false


compiler:
  - gcc
  - clang

cache: apt


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=false"
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false -DWITH_ITK=false"
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libboost-program-options-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libboost-system-dev
    - libgmp-dev
    - libgdcm2-dev 
    - libgraphicsmagick++1-dev
    - libqglviewer-qt4-dev
    - libinsighttoolkit3-dev 

before_script:
  - cd ..
  - git clone git://github.com/DGtal-team/DGtal.git
  - mkdir LibDGtal;
  - cd DGtal
  - mkdir build; cd build
  - cmake .. $DGTALTYPE 
  - make 
  - cd ../../DGtalTools

script: 
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$HOME/DGtal/build
  - make
